In [2]:
import pandas as pd
import numpy as np
import torch


In [3]:
print(torch.__version__)

2.3.0+cpu


In [4]:
!nvidia-smi

Wed May 15 16:18:09 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.23       Driver Version: 442.23       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX230      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   75C    P8    N/A /  N/A |     63MiB /  2048MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Creating Tensors

In [6]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [12]:
#vector

vector = torch.tensor([1,2,3,4,5])
vector
vector.ndim


1

In [13]:
vector.shape

torch.Size([5])

In [14]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
## Random Tensors

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3759, 0.2661, 0.3101, 0.0745],
        [0.5923, 0.9192, 0.9861, 0.1676],
        [0.3046, 0.0826, 0.1030, 0.7051]])

In [31]:
random_tensor.ndim

2

In [36]:
# create a random tensor with a similar shape to image tensor

image = torch.rand(size=(224, 224,3))

image.ndim


3

In [37]:
image.shape

torch.Size([224, 224, 3])

In [40]:
# Zeros & ones

zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
ones=torch.ones(2,3,2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [49]:
ones.dtype, ones.ndim

(torch.float32, 3)

In [53]:
# create a range of tensors & tensors-like

one_to_ten= torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#Tensors-like

ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors Datatypes

In [55]:
float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=None,device = None, 
                        requires_grad=False)

float_32



tensor([3., 6., 9.])

In [58]:
float_32.dtype

torch.float32

In [59]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [60]:
float_16*float_32

tensor([ 9., 36., 81.])

In [61]:
# Getting information from tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6687, 0.9153, 0.8713, 0.5800],
        [0.0039, 0.5858, 0.2880, 0.3388],
        [0.0225, 0.8210, 0.1935, 0.4827]])

In [65]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.size)
print(some_tensor.device)


tensor([[0.6687, 0.9153, 0.8713, 0.5800],
        [0.0039, 0.5858, 0.2880, 0.3388],
        [0.0225, 0.8210, 0.1935, 0.4827]])
torch.float32
<built-in method size of Tensor object at 0x0000028E77914CC0>
cpu
