In [2]:
import pandas as pd
import numpy as np
import torch


In [3]:
print(torch.__version__)

2.3.0+cpu


In [4]:
!nvidia-smi

Wed Jun  5 17:20:32 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.85                 Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX230         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   61C    P3             N/A / ERR!  |       0MiB /   2048MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Creating Tensors

In [5]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
#vector

vector = torch.tensor([1,2,3,4,5])
vector
vector.ndim


1

In [9]:
vector.shape

torch.Size([5])

In [10]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
## Random Tensors

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.7195, 0.6342, 0.8683, 0.1032],
        [0.9015, 0.7155, 0.4903, 0.2946],
        [0.6519, 0.9228, 0.5336, 0.2329]])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with a similar shape to image tensor

image = torch.rand(size=(224, 224,3))

image.ndim


3

In [21]:
image.shape

torch.Size([224, 224, 3])

In [22]:
# Zeros & ones

zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones=torch.ones(2,3,2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [24]:
ones.dtype, ones.ndim

(torch.float32, 3)

In [25]:
# create a range of tensors & tensors-like

one_to_ten= torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Tensors-like

ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors Datatypes

In [27]:
float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=None,device = None, 
                        requires_grad=False)

float_32



tensor([3., 6., 9.])

In [28]:
float_32.dtype

torch.float32

In [29]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16*float_32

tensor([ 9., 36., 81.])

In [31]:
# Getting information from tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9883, 0.5396, 0.1065, 0.5145],
        [0.7159, 0.8357, 0.2116, 0.8849],
        [0.7172, 0.2292, 0.6661, 0.0914]])

In [32]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.size)
print(some_tensor.device)


tensor([[0.9883, 0.5396, 0.1065, 0.5145],
        [0.7159, 0.8357, 0.2116, 0.8849],
        [0.7172, 0.2292, 0.6661, 0.0914]])
torch.float32
<built-in method size of Tensor object at 0x00000179A7F8C360>
cpu


## Manipulating tensors

 Tensors operations include addition, subtractition,Multiplication,Division & matrix multiplication



In [33]:
tensor = torch.tensor([1,2,3])
scalar_tensor = torch.tensor(10)

tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

Multiplication can be done in 2 ways.
Element wise multiplication & matrix multiplication.

In [36]:
print(tensor * tensor)

tensor([1, 4, 9])


In [37]:
#Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

condition to satisfy matrix multiplication :

Inner dimesnsion should be same.
(3,2) @ (3,2) wont work
(3,2) @ (2,3) will work

THE RESULTING MATRIX HAS THE SHAPE OF **OUTER DIMENSION**


In [38]:
# SHAPES for matrix multiplication

tensor_a = torch.tensor([[1,2],[3,4],[5,6]])

tensor_b = torch.tensor([[7,10],[8,11],[9,12]])



torch.mm(tensor_a,tensor_b.T)


# torch.mm(tensor_a,tensor_b) WILL NOT WORK


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [39]:
tensor_a.shape , tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues we can manipulate the shape of one of the tensors using **TRANSPOSE** 

In [40]:
tensor_b.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [41]:
tensor_b.T.shape

torch.Size([2, 3])

## Tensor Aggregation

In [42]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
torch.min(x)

tensor(0)

In [44]:
torch.max(x)

tensor(90)

In [45]:
x.dtype

torch.int64

In [46]:
#torch.mean(x) wont work 

torch.mean(x.type(torch.float32)),

x.type(torch.float32).mean()

tensor(45.)

In [47]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [48]:
#positional min & max

x.argmin(), x.argmax(), 

(tensor(0), tensor(9))

# Reshaping, stacking , squeezeing and unsqueezing

Reshaping- reshapes an input to a defined shape

stacking- combine multiple tensor on top of each other
hstack, vstack

squeezeing- removes the dimension of size 1

unsqueezing- adds the dimension of size 1





In [49]:
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [50]:
y = x.reshape(5,2)
y

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [51]:
#stack

x_stacked = torch.stack([x,x,x,x])

x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [52]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [53]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [54]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [55]:
y = torch.squeeze(x, 1)
y.size()


torch.Size([2, 2, 1, 2])

In [56]:
# torch.permute (mostly used for images)

x = torch.randn(2, 3, 5)
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

### INDEXING

In [57]:
import torch

x = torch.arange(1,10).reshape(1,3,3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
x[0][0]

tensor([1, 2, 3])

In [60]:
x[0][0][0]

tensor(1)

In [61]:
x[:,:,1]

tensor([[2, 5, 8]])

In [62]:
x[:,1,1]

tensor([5])

In [63]:
x[0,0,:]

tensor([1, 2, 3])

In [64]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [65]:
x[0,2,2]

tensor(9)

In [66]:
x[:,:,2]

tensor([[3, 6, 9]])

In [67]:
## Pytorch & Numpy

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
array = array = 1
array, tensor

(1, tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility 

Taking random out of random

In [70]:
torch.rand(3,3)

tensor([[0.1360, 0.3556, 0.6225],
        [0.9499, 0.5842, 0.4590],
        [0.8293, 0.1949, 0.4155]])

In [71]:
a = torch.rand(3,4)
b = torch.rand(3,4)

print(a)
print(b)
print(a==b)

tensor([[0.9122, 0.4976, 0.4674, 0.2261],
        [0.3415, 0.7289, 0.6547, 0.4504],
        [0.6258, 0.9917, 0.5570, 0.3534]])
tensor([[0.5466, 0.4412, 0.5262, 0.3895],
        [0.9837, 0.1125, 0.8399, 0.1694],
        [0.6657, 0.6675, 0.0935, 0.6794]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
torch.manual_seed(42)
a = torch.rand(3,4)

torch.manual_seed(42)
b = torch.rand(3,4)

print(a)
print(b)

print(a==b)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [73]:
## GPUS using

import torch
print(torch.cuda.is_available())


False


# Py Torch Workflow


In [74]:
import torch
from torch import nn 
import matplotlib.pyplot as plt
import numpy as np

In [75]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02

X = torch.arange(start,end,step).unsqueeze(dim=1)
y = weight * X + bias
 

X[:10], y[:10] , len(X), len(y) 

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]),
 50,
 50)

In [76]:
#splitting data into train and test

train_split = int(0.8*len(X))

X_train, y_train = X[:train_split], y[:train_split]

X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)


(40, 40, 10, 10)

In [77]:
class LinearRegression(nn.Module):

    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1,requires_grad=True, 
                                dtype=torch.float))
        
        self.bias = nn.Parameter(torch.randn(1,requires_grad=True, 
                                dtype=torch.float))
        
        #Forward method to define the computation in the moedel
    def forward(self,x: torch.Tensor) -> torch.Tensor:
        return self.weights * x + self.bias 
    

### PYTORCH MODEL BUILDING ESSENTIALS

torch.nn - Contains all of the buildings for computational graphs(a neural network can be considered a computational graph)

torch.optim - Contains all of the optimization algorithms

torch.nn.functional - Contains all of the non-computational layers

torch.utils - Contains utilities for working with data

torch.tensor - Creates a tensor representing            

torch.autograd - Contains all of the autograd functionality

torch.optim - Contains all of the optimization algorithms

torch.nn.module - The base class for all neural network modules, if subwrite it, should overwrite forward.



In [78]:
# checking pytorch model

torch.manual_seed(42)

model_0  = LinearRegression()

list(model_0.parameters())


[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [79]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [80]:
#Making prediction

with torch.inference_mode(): #for predictions
    
    y_pred = model_0(X_test)

y_pred

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [81]:
print(y_test)

y_test - y_pred

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])


tensor([[0.4618],
        [0.4691],
        [0.4764],
        [0.4836],
        [0.4909],
        [0.4982],
        [0.5054],
        [0.5127],
        [0.5200],
        [0.5272]])

In [82]:
# Training the model

model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [105]:
#setup loss function

loss_fn = nn.L1Loss()

#OPTIMIZER

optimizer = torch.optim.SGD(model_0.parameters(), lr=0.1)


In [131]:
epochs = 200

for epoch in range(epochs):

    model_0.train()

    #forward pass
    y_pred = model_0(X_train)

    #calculate the loss function
    loss = loss_fn(y_pred, y_train)
    

    #optimizer zero grad
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #optimizer step
    optimizer.step()


    model_0.eval() #turns off different setting in model that are not needed for model evaluation

    with torch.inference_mode(): #turns off gradients tracking
        test_pred = model_0(X_test)

        test_loss = loss_fn(test_pred, y_test)

    if epoch % 10 == 0:  
        
        print(f"Epoch: {epoch} | Test Loss: {test_loss} |Loss :{loss}")

Epoch: 0 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 10 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 20 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 30 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 40 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 50 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 60 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 70 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 80 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 90 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 100 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 110 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 120 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epoch: 130 | Test Loss: 0.06481156498193741 |Loss :0.039163630455732346
Epo

In [132]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.6385])), ('bias', tensor([0.2848]))])

## Saving and loading model in pytorch

In [134]:
from pathlib import Path

# create the model directory

Model_Path = Path('models')
Model_Path.mkdir(parents=True, exist_ok=True)

# Create model save path

Model_name = '01_pytorch_model.pth'

model_save_path = Model_Path / Model_name

model_save_path

#save model

torch.save(model_0.state_dict(), model_save_path)

In [138]:
model_0.state_dict()

OrderedDict([('weights', tensor([0.6385])), ('bias', tensor([0.2848]))])

In [139]:
# to load in a saved state_dict we have to instantiate a new instance of the model

loaded_model_0 = LinearRegression()

In [142]:
loaded_model_0.load_state_dict(torch.load(f=model_save_path))

<All keys matched successfully>

In [143]:
loaded_model_0.state_dict()

OrderedDict([('weights', tensor([0.6385])), ('bias', tensor([0.2848]))])

In [144]:
#predicting with our loaded model

loaded_model_0.eval()

with torch.inference_mode():
    loaded_model_preds = loaded_model_0(X_test)

loaded_model_preds

tensor([[0.7956],
        [0.8084],
        [0.8212],
        [0.8339],
        [0.8467],
        [0.8595],
        [0.8723],
        [0.8850],
        [0.8978],
        [0.9106]])

In [146]:
#compare loaded model pred with original model

y_pred == loaded_model_preds



tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])

## Classification with Pytorch