In [2]:
import pandas as pd
import numpy as np
import torch


In [3]:
print(torch.__version__)

2.3.0+cpu


In [4]:
!nvidia-smi

Mon May 20 17:48:41 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.23       Driver Version: 442.23       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX230      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   65C    P8    N/A /  N/A |     63MiB /  2048MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Creating Tensors

In [5]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
#vector

vector = torch.tensor([1,2,3,4,5])
vector
vector.ndim


1

In [9]:
vector.shape

torch.Size([5])

In [10]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
## Random Tensors

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.5585, 0.9900, 0.1830, 0.9870],
        [0.1449, 0.4468, 0.8311, 0.0372],
        [0.3222, 0.2143, 0.7215, 0.2161]])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with a similar shape to image tensor

image = torch.rand(size=(224, 224,3))

image.ndim


3

In [21]:
image.shape

torch.Size([224, 224, 3])

In [22]:
# Zeros & ones

zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones=torch.ones(2,3,2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [24]:
ones.dtype, ones.ndim

(torch.float32, 3)

In [25]:
# create a range of tensors & tensors-like

one_to_ten= torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Tensors-like

ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors Datatypes

In [27]:
float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=None,device = None, 
                        requires_grad=False)

float_32



tensor([3., 6., 9.])

In [28]:
float_32.dtype

torch.float32

In [29]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16*float_32

tensor([ 9., 36., 81.])

In [31]:
# Getting information from tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8686, 0.0482, 0.8048, 0.4779],
        [0.0472, 0.2368, 0.8716, 0.0558],
        [0.4551, 0.3943, 0.2264, 0.8318]])

In [32]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.size)
print(some_tensor.device)


tensor([[0.8686, 0.0482, 0.8048, 0.4779],
        [0.0472, 0.2368, 0.8716, 0.0558],
        [0.4551, 0.3943, 0.2264, 0.8318]])
torch.float32
<built-in method size of Tensor object at 0x000001D2A2459180>
cpu


## Manipulating tensors

 Tensors operations include addition, subtractition,Multiplication,Division & matrix multiplication



In [33]:
tensor = torch.tensor([1,2,3])
scalar_tensor = torch.tensor(10)

tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

Multiplication can be done in 2 ways.
Element wise multiplication & matrix multiplication.

In [38]:
print(tensor * tensor)

tensor([1, 4, 9])


In [39]:
#Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

condition to satisfy matrix multiplication :

Inner dimesnsion should be same.
(3,2) @ (3,2) wont work
(3,2) @ (2,3) will work

THE RESULTING MATRIX HAS THE SHAPE OF **OUTER DIMENSION**


In [46]:
# SHAPES for matrix multiplication

tensor_a = torch.tensor([[1,2],[3,4],[5,6]])

tensor_b = torch.tensor([[7,10],[8,11],[9,12]])



torch.mm(tensor_a,tensor_b.T)


# torch.mm(tensor_a,tensor_b) WILL NOT WORK


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [41]:
tensor_a.shape , tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues we can manipulate the shape of one of the tensors using **TRANSPOSE** 

In [44]:
tensor_b.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [45]:
tensor_b.T.shape

torch.Size([2, 3])

## Tensor Aggregation

In [50]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
torch.min(x)

tensor(0)

In [49]:
torch.max(x)

tensor(90)

In [51]:
x.dtype

torch.int64

In [55]:
#torch.mean(x) wont work 

torch.mean(x.type(torch.float32)),

x.type(torch.float32).mean()

tensor(45.)

In [57]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [58]:
#positional min & max

x.argmin(), x.argmax(), 

(tensor(0), tensor(9))

# Reshaping, stacking , squeezeing and unsqueezing

Reshaping- reshapes an input to a defined shape

stacking- combine multiple tensor on top of each other
hstack, vstack

squeezeing- removes the dimension of size 1

unsqueezing- adds the dimension of size 1





In [60]:
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [62]:
y = x.reshape(5,2)
y

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [65]:
#stack

x_stacked = torch.stack([x,x,x,x])

x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [67]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [68]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [69]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [71]:
y = torch.squeeze(x, 1)
y.size()


torch.Size([2, 2, 1, 2])

In [72]:
# torch.permute (mostly used for images)

x = torch.randn(2, 3, 5)
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

### INDEXING

In [2]:
import torch

x = torch.arange(1,10).reshape(1,3,3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
x[0][0]

tensor([1, 2, 3])

In [6]:
x[0][0][0]

tensor(1)

In [7]:
x[:,:,1]

tensor([[2, 5, 8]])

In [8]:
x[:,1,1]

tensor([5])

In [9]:
x[0,0,:]

tensor([1, 2, 3])

In [10]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
x[0,2,2]

tensor(9)

In [12]:
x[:,:,2]

tensor([[3, 6, 9]])

In [14]:
## Pytorch & Numpy

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [15]:
array = array = 1
array, tensor

(1, tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility 

Taking random out of random

In [17]:
torch.rand(3,3)

tensor([[0.4192, 0.8261, 0.1952],
        [0.8444, 0.1815, 0.6885],
        [0.9969, 0.2611, 0.6134]])

In [20]:
a = torch.rand(3,4)
b = torch.rand(3,4)

print(a)
print(b)
print(a==b)

tensor([[0.9309, 0.6103, 0.9022, 0.6031],
        [0.0628, 0.5213, 0.5279, 0.9946],
        [0.0788, 0.7536, 0.6840, 0.5738]])
tensor([[0.2672, 0.2123, 0.5005, 0.3385],
        [0.3966, 0.6899, 0.7675, 0.5168],
        [0.9983, 0.2347, 0.7550, 0.6237]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [21]:
torch.manual_seed(42)
a = torch.rand(3,4)

torch.manual_seed(42)
b = torch.rand(3,4)

print(a)
print(b)

print(a==b)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
## GPUS using

import torch
print(torch.cuda.is_available())


False
