In [2]:
import pandas as pd
import numpy as np
import torch


In [3]:
print(torch.__version__)

2.3.0+cpu


In [4]:
!nvidia-smi

Wed May 15 18:08:34 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.23       Driver Version: 442.23       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce MX230      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   58C    P8    N/A /  N/A |     63MiB /  2048MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Creating Tensors

In [5]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
#vector

vector = torch.tensor([1,2,3,4,5])
vector
vector.ndim


1

In [9]:
vector.shape

torch.Size([5])

In [10]:
#MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
## Random Tensors

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1828, 0.0265, 0.5321, 0.6616],
        [0.1339, 0.2599, 0.7956, 0.3559],
        [0.9002, 0.9088, 0.7294, 0.7951]])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with a similar shape to image tensor

image = torch.rand(size=(224, 224,3))

image.ndim


3

In [21]:
image.shape

torch.Size([224, 224, 3])

In [22]:
# Zeros & ones

zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones=torch.ones(2,3,2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [24]:
ones.dtype, ones.ndim

(torch.float32, 3)

In [25]:
# create a range of tensors & tensors-like

one_to_ten= torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Tensors-like

ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors Datatypes

In [27]:
float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=None,device = None, 
                        requires_grad=False)

float_32



tensor([3., 6., 9.])

In [28]:
float_32.dtype

torch.float32

In [29]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16*float_32

tensor([ 9., 36., 81.])

In [31]:
# Getting information from tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3138, 0.9553, 0.9512, 0.8497],
        [0.9951, 0.8758, 0.0358, 0.4490],
        [0.5525, 0.5397, 0.0595, 0.1089]])

In [32]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.size)
print(some_tensor.device)


tensor([[0.3138, 0.9553, 0.9512, 0.8497],
        [0.9951, 0.8758, 0.0358, 0.4490],
        [0.5525, 0.5397, 0.0595, 0.1089]])
torch.float32
<built-in method size of Tensor object at 0x000001351C34FAE0>
cpu


## Manipulating tensors

 Tensors operations include addition, subtractition,Multiplication,Division & matrix multiplication



In [36]:
tensor = torch.tensor([1,2,3])
scalar_tensor = torch.tensor(10)

tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([-9, -8, -7])